# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Roomies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roomies
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'iOSDropDown'
  target 'RoomiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoomiesUITests' do
    # Pods for testing
  end

end
